First commit with tests
HolyDani/Otus_Go_hw pull request #5
Opened 2024-11-16 20:11 UTC by HolyDani

## Домашнее задание №6 «Покрыть тестами предыдущие задания»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 4 баллов

2024-11-16 20:57 UTC, vladislavmass requested changes

2024-11-16 20:57 UTC, vladislavmass commented on hw06_testing/hw04/book/book_test.go
> +func TestCompareBooks(t *testing.T) {
На самом деле все, что выше 97 строки вообще не нужно. Никто не тестирует конструкторы, геттеры и сеттеры. Так как чаще всего у них очень простой функционал

2024-11-16 20:57 UTC, vladislavmass commented on hw06_testing/hw05/shapes/circle/circle_test.go
> +func TestNewCircle(t *testing.T) {
Тесты на конструктор на нужны

2024-11-16 20:57 UTC, vladislavmass commented on hw06_testing/hw05/shapes/rectangle/rectangle_test.go
> +func TestNewRectangle(t *testing.T) {
Тесты на конструктор на нужны

2024-11-16 20:57 UTC, vladislavmass commented on hw06_testing/hw05/shapes/triangle/triangle_test.go
> +func TestNewTriangle(t *testing.T) {
Тесты на конструктор на нужны

2024-11-16 20:57 UTC, vladislavmass commented on hw06_testing/hw05/calculateArea_test.go
> +			shape:        nil,
Не надо использовать nil в тестах. Лучше использовать например пустую структуру.

2024-11-16 20:57 UTC, vladislavmass commented on hw06_testing/hw03/chessboard.go
> +				board += "#"
Складывать вот так строки не очень хорошая идея так как в go строки неизменяемый тип данных и поэтому каждая конкуренция приводит к выделению памяти и копированию. Лучше использовать strings.Builder

2024-11-16 20:57 UTC, vladislavmass commented on hw06_testing/hw02/reader/reader.go
> +func ReadJSON(filePath string) ([]types.Employee, error) {
Этот метод нужно покрыть тестами.

2024-11-16 20:57 UTC, vladislavmass commented on hw06_testing/hw02/reader/reader.go
> +		fmt.Printf("Error: %v", err)
Тут нужно вернуть ошибку вызывающему коду, иначе попытка прочитать неоткрытый файл ничем хорошим не закончится

2024-11-16 20:57 UTC, vladislavmass commented on hw06_testing/hw02/reader/reader.go
> +		return nil, nil
Ошибку нужно прокинуть в вызывающий код, что бы он мог на нее среагировать

2024-11-16 20:57 UTC, vladislavmass commented on hw06_testing/hw02/reader/reader.go
> +		return nil, nil
Ошибку нужно прокинуть в вызывающий код, что бы он мог на нее среагировать

2024-11-16 20:57 UTC, vladislavmass commented on hw06_testing/hw02/printer/printer.go
> +	fmt.Println(str)
А вот эта строка тут зачем?

2024-11-17 08:58 UTC, HolyDani commented on hw06_testing/hw05/calculateArea_test.go
> +			shape:        nil,
Для ошибок nil тоже не рекомендуется в тестах?

2024-11-17 09:00 UTC, hungry-honeybadger commented on hw06_testing/hw05/calculateArea_test.go
> +			shape:        nil,
Для ошибок можно использовать nil

2024-11-17 09:02 UTC, vladislavmass commented on hw06_testing/hw05/calculateArea_test.go
> +			shape:        nil,
условно говоря если nil это значение на равенство или отличие которого мы будем проверить то норм, а вот если nil мы пытаемся использовать как структуру( как в данном случае) то это уже не норм

2024-11-17 12:25 UTC, HolyDani commented on hw06_testing/hw02/reader/reader.go
> +func ReadJSON(filePath string) ([]types.Employee, error) {
@vladislavmass А как обработать ожидаемую ошибку? Я просто не понимаю что писать в поле expectedErr:

2024-11-17 12:26 UTC, vladislavmass commented on hw06_testing/hw02/reader/reader.go
> +func ReadJSON(filePath string) ([]types.Employee, error) {
В данном случае просто проверьте что ошибка не равна nil

2024-11-18 06:35 UTC, vladislavmass approved these changes

2024-11-18 06:48 UTC, merged